name: Build Astro and Upload to FTP

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v2
      - name: Use Node.js 19
        uses: actions/setup-node@v2
        with:
          node-version: "19"
      - name: Build Project
        run: |
          npm install
          npm run build
      - name: List files
        run: |
          ls -la
      - name: Upload FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: "www"
